### ISSUE TITLE
General Roadmap

### ISSUE THREAD

**Issue by pkos98** [pkos98/book4less#1]
- [ ] Integrate other book-stores
  - [x] Integrate medimops f3124eb7e84c208cecd2297cec41f598481049d3
  - [ ] Integrate rebuy
  - [ ] Integrate booklooker
- [ ] Track progress of search
- [ ] Run each search concurrently (so in it's own beam-process)
- [ ] Provide search-suggestions
